### PR TITLE
LICENSE.md

### PR DESCRIPTION
**Pull request by TrickJoker312**

### CODE REVIEW

**Review by fartsindogs — APPROVED** [review]
E

**Review by fartsindogs — APPROVED** [review]
e

**Comment by fartsindogs** [comment]
you need to merge it

**Comment by TrickJoker312** [comment]
It has to get reviewed.

**Review by Deus-Scissuras — APPROVED** [review]

**Review by Deus-Scissuras — COMMENTED** [review]
I think you can merge it now

**Comment by 3kh0** [comment]
why tf would you put a license on a list of links?

**Pull request closed without merging**
