### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by UpTiGamer**

### CODE REVIEW

**Comment by UpTiGamer** [comment]
@TrickJoker312 add

**Comment by Asleep123** [comment]
mind sharing your discord username? need to contact you about something.

**Comment by UpTiGamer** [comment]
> mind sharing your discord username? need to contact you about something.

what is discord brother

**Comment by Asleep123** [comment]
> > mind sharing your discord username? need to contact you about something.
> 
> what is discord brother

who gave you that link? link leaking isn’t allowed,  and we need to know who gave you it so we can get in contact so we can get in contact with them

**Comment by UpTiGamer** [comment]
> > > mind sharing your discord username? need to contact you about something.
> > 
> > 
> > what is discord brother
> 
> who gave you that link? link leaking isn’t allowed, and we need to know who gave you it so we can get in contact so we can get in contact with them

a comment on 3kh0 youtube

**Comment by Asleep123** [comment]
> > > mind sharing your discord username? need to contact you about something.
> > 
> > 
> > what is discord brother
> 
> who gave you that link? link leaking isn’t allowed, and we need to know who gave you it so we can get in contact so we can get in contact with them
can you send a link to that video? i’ll ask 3kh0 to take it down

**Comment by UpTiGamer** [comment]
> > > mind sharing your discord username? need to contact you about something.
> > 
> > 
> > what is discord brother
> 
> who gave you that link? link leaking isn’t allowed, and we need to know who gave you it so we can get in contact so we can get in contact with them can you send a link to that video? i’ll ask 3kh0 to take it down
it was in persian and i don't remember the name but it gave me so many proxies

**Pull request closed without merging**
